services:
  app:
    container_name: palmer-devops
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production

networks:
  app-network:
    driver: bridge